### PR TITLE
Added navigation and grids

### PR DESCRIPTION
**Pull request by srishti-maurya**
Added components
- navigation
- grids

Live preview - https://srishti-maurya.github.io/Plan-it-Component-Library/

### CODE REVIEW

**Review by msdeshmukh009 — APPROVED** [review]
Good to go. Nice work!!

**Review by sanathkumar26700 — APPROVED** [review]
✅ Clean code
✅ Clean UI
✅ Everything working fine

**Review by Chakravarthi0 — APPROVED** [review]
looks good to me

**Comment by KaustubhM1997** [comment]
Looks great, please proceed!

**Review by MarkVed17 — APPROVED** [review]
Good to proceed!

**Pull request merged**
