### PR TITLE
feat: added docs for CL and routes

### PR DESCRIPTION
**Pull request by srishti-maurya**
Here all the documentation part for the website and the P0 components is done.
Your suggestion and review is highly appreciated and welcomed, to improve it further.
Note : I will add responsiveness in the end.
Live Preview: https://srishti-maurya.github.io/Plan-it-Component-Library/

### CODE REVIEW

**Review by Varu98 — APPROVED** [review]
This looks great!!

suggestion:- Increase padding on the footer just a little, also you can give a bolder font-weight to the buttons to increase accessibility.

**Review by manojasarsa — APPROVED** [review]
Few small suggestions that would make the CL look more awesome:
- Little bit top margin for logo
- left and right margins for social media icons
- For "Home & Documentation" in nav left margin can be given
- top and bottom padding in footer
- For Color and Conclusions TAB -- Footer is not sticking to bottom (if done, will look great)

Rest, I liked the UI. Good to go 👍

**Review by msdeshmukh009 — APPROVED** [review]
I think the UI is looking overall consistent. Great work!! . You can work on suggestions given by @manojasarsa  and @Varu98

**Comment by preethasri** [comment]
looks neat and clean👍

**Pull request merged**
