### PR TITLE
Comp/image input card

### PR DESCRIPTION
**Pull request by srishti-maurya**
These are just components, the documentation is not added yet!

Screenshots is attached for reference below.

Any suggestion/feedback would be highly appreciated.

View Live at : https://srishti-maurya.github.io/Plan-it-Component-Library/

images
inputs
cards

### CODE REVIEW

**Review by poornima-alugubelly — APPROVED** [review]
Looks good Srishti !

**Review by manojasarsa — APPROVED** [review]
Looks good! Just a quick suggestion, align the components and text little in center or give some left margin to all components and text, it will make them look more readable.

**Comment by preethasri** [comment]
Looks good srishti

**Comment by vijaytembugade** [comment]
Looks good srishti. I would like to ask you to right media queries too while building components. It will help you in future that you dont have to come back and add them for responsiveness.

**Pull request merged**
